#general setting
url: "https://minyoung-mia-kim.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "MINYOUNG KIM" # the name of your site, e.g. ACME Corp.
description: "ğŸ‘©â€ğŸ’» Ph.D. student ğŸ’» @ George Mason Univeristy"
cc: by

# author
email: mkim229@gmu.edu
curriculum: 
- url: /assets/doc/CV.pdf
shortbio: "test shortbio"
github_username: "minyoung-mia-kim.github.io"
#linkedin_username:

